### ISSUE TITLE
SISSEGV calling libuast.filter

### ISSUE THREAD

**Issue by erizocosmico** [bblfsh/client-scala#30]
Full crash report: https://gist.github.com/erizocosmico/6e318f3dfdf7e119e449c14f6d969572

How to reproduce this issue:

```
git clone https://github.com/src-d/spark-api.git
cd spark-api
make docker-build && make docker-run
```

Then access the URL that's printed in the console and run the first step and the last 3 (ctrl+enter).

Haven't tried yet with 1.3.0 of client-scala.

**Comment by juanjux** [comment]
Should be fixed in 1.3.2.

**Comment by erizocosmico** [comment]
Can confirm it's fixed. Don't know how in hell's name you debugged this but u my hero.

**Comment by juanjux** [comment]
Mostly using the power of `println` :)
