### ISSUE TITLE
Add support to query supported languages (with installed drivers)

### ISSUE THREAD

**Issue by smola** [bblfsh/client-scala#68]
In some applications, it is very useful to know which languages are supported (with installed drivers) beforehand. This helps to:

* Display lists of supported languages in UX elements.
* Reduce number of requests to bblfshd by avoiding requests for unsupported languages.

It would be nice to have such functionality implemented in the Scala client.

**Comment by dpordomingo** [comment]
We have that necessity for https://github.com/bblfsh/dashboard/issues/89 too.
It [was proposed](https://github.com/bblfsh/dashboard/issues/89#issuecomment-351655057) to use the `github.com/bblfsh/bblfshd/daemon/protocol.ProtocolServiceClient`, but it currently runs over a unix socket so it is not reachable from the outside of the bblfsh container.

**Comment by bzz** [comment]
Indeed we need this, but for golang client first :)

This makes me think - do you guys think this is the right repo to track this, or is there a better one if changes are required on a protocol-level?

**Comment by juanjux** [comment]
Closing since we just got a duplicated in the SDK

sdk/issues/253

**Comment by juanjux** [comment]
Still needs to be integrated in the client, reopening.
