### ISSUE TITLE
Rename to scala-client

### ISSUE THREAD

**Issue by dennwc** [bblfsh/client-scala#86]
To make it consistent with drivers, we should rename the repository to `scala-client`.

**Comment by bzz** [comment]
Please, let's not do this until:
  1. there is a consensus on the value of this change
  2.https://github.com/bblfsh/client-python is removed

**Comment by dennwc** [comment]
Unfortunately, I cannot find a link to attach to the first point, although I'm pretty sure this was discussed before and was the reasoning behind the `go-driver` rename.

In any case, this is not critical and can wait until we have time to do this.

**Comment by dennwc** [comment]
Found the umbrella issue: https://github.com/bblfsh/documentation/issues/231

**Comment by bzz** [comment]
https://github.com/bblfsh/scala-client
